/* ELAN SPORT — Données produits (catalogue statique)
   Chaque produit a une catégorie, un prix, un tag optionnel et une palette
   de couleurs utilisée pour générer sa vignette (pas de photos = pas de
   dépendance réseau, mais un rendu graphique cohérent). */

const PRODUCTS = [
  {
    id: "p01",
    name: "Veste Coupe-Vent Aeroflex",
    category: "running",
    price: 79.9,
    oldPrice: null,
    tag: "Bestseller",
    icon: "jacket",
    colors: ["#c6ff3d", "#1b1f14"],
  },
  {
    id: "p02",
    name: "T-Shirt Technique DryFit",
    category: "running",
    price: 29.9,
    oldPrice: 39.9,
    tag: "Promo",
    icon: "tshirt",
    colors: ["#2e6bff", "#0b1030"],
  },
  {
    id: "p03",
    name: "Legging Sculpt Pro",
    category: "fitness",
    price: 44.9,
    oldPrice: null,
    tag: "Nouveau",
    icon: "legging",
    colors: ["#ff4d2e", "#2a0a06"],
  },
  {
    id: "p04",
    name: "Short Performance 2-en-1",
    category: "running",
    price: 34.9,
    oldPrice: null,
    tag: null,
    icon: "short",
    colors: ["#c6ff3d", "#10130a"],
  },
  {
    id: "p05",
    name: "Brassière Flex Support",
    category: "fitness",
    price: 27.9,
    oldPrice: null,
    tag: "Bestseller",
    icon: "bra",
    colors: ["#ff8a00", "#231000"],
  },
  {
    id: "p06",
    name: "Hoodie Street Elan",
    category: "streetwear",
    price: 64.9,
    oldPrice: null,
    tag: "Nouveau",
    icon: "hoodie",
    colors: ["#8a8f98", "#0d0e10"],
  },
  {
    id: "p07",
    name: "Sweat Zippé Urban",
    category: "streetwear",
    price: 59.9,
    oldPrice: 74.9,
    tag: "Promo",
    icon: "zip",
    colors: ["#2e6bff", "#060a1a"],
  },
  {
    id: "p08",
    name: "Legging Yoga Flow",
    category: "yoga",
    price: 42.9,
    oldPrice: null,
    tag: null,
    icon: "legging",
    colors: ["#ff4d2e", "#160504"],
  },
  {
    id: "p09",
    name: "Débardeur Souplesse",
    category: "yoga",
    price: 24.9,
    oldPrice: null,
    tag: null,
    icon: "tank",
    colors: ["#c6ff3d", "#0c0f08"],
  },
  {
    id: "p10",
    name: "Baskets Trail Runner X1",
    category: "running",
    price: 99.9,
    oldPrice: null,
    tag: "Bestseller",
    icon: "shoe",
    colors: ["#ff8a00", "#1a0f00"],
  },
  {
    id: "p11",
    name: "Casquette Performance",
    category: "streetwear",
    price: 19.9,
    oldPrice: null,
    tag: null,
    icon: "cap",
    colors: ["#8a8f98", "#101114"],
  },
  {
    id: "p12",
    name: "Gilet Sans Manches Aero",
    category: "fitness",
    price: 54.9,
    oldPrice: 69.9,
    tag: "Promo",
    icon: "vest",
    colors: ["#2e6bff", "#020614"],
  },
];

const CATEGORY_LABELS = {
  running: "Running",
  fitness: "Fitness",
  yoga: "Yoga",
  streetwear: "Streetwear",
};
