/* =========================================================
   UNDERCOVER — Dictionnaire de paires de mots (français)
   ---------------------------------------------------------
   Chaque paire contient deux mots proches : les civils
   reçoivent l'un, les undercovers reçoivent l'autre.
   L'ordre des deux mots n'a pas d'importance : le jeu tire
   au sort lequel revient aux civils.

   Niveaux de difficulté :
   - facile    : les deux mots n'ont presque rien en commun,
                 l'imposteur se trahit très vite.
   - moyen     : même famille d'idées, il faut rester vague.
   - difficile : mots quasi synonymes, bluff obligatoire.
   ========================================================= */

const UNDERCOVER_WORDS = {
  facile: [
    ["Chien", "Poisson"],
    ["Soleil", "Parapluie"],
    ["Pizza", "Salade"],
    ["Guitare", "Tambour"],
    ["Avion", "Vélo"],
    ["Plage", "Bibliothèque"],
    ["Neige", "Désert"],
    ["Chocolat", "Citron"],
    ["Montre", "Oreiller"],
    ["Football", "Échecs"],
    ["Pompier", "Boulanger"],
    ["Château", "Cabane"],
    ["Téléphone", "Bougie"],
    ["Lion", "Lapin"],
    ["Café", "Soupe"],
    ["Mariage", "Examen"],
    ["Voiture", "Cheval"],
    ["Supermarché", "Musée"],
    ["Glace", "Barbecue"],
    ["Clavier", "Pinceau"],
    ["Dentiste", "Jardinier"],
    ["Ascenseur", "Échelle"],
    ["Pyjama", "Costume"],
    ["Orage", "Arc-en-ciel"],
    ["Banque", "Boulangerie"],
    ["Astronaute", "Plombier"],
    ["Crayon", "Marteau"],
    ["Forêt", "Métro"],
    ["Miel", "Vinaigre"],
    ["Tortue", "Guépard"],
    ["Aéroport", "Camping"],
    ["Télévision", "Cheminée"],
    ["Moustique", "Éléphant"],
    ["Pluie", "Feu de camp"],
    ["Hôpital", "Discothèque"],
    ["Fromage", "Dentifrice"],
    ["Bateau", "Fusée"],
    ["Sieste", "Marathon"],
    ["Fourchette", "Savon"],
    ["Cirque", "Tribunal"],
    ["Ampoule", "Chaussette"],
    ["Balançoire", "Tondeuse"],
    ["Anniversaire", "Déménagement"],
    ["Pastèque", "Poivre"],
    ["Tunnel", "Montgolfière"],
    ["Journal", "Trampoline"],
    ["Ninja", "Bibliothécaire"],
    ["Réveil", "Hamac"],
    ["Souris", "Requin"],
    ["Parfum", "Poubelle"]
  ],

  moyen: [
    ["Café", "Thé"],
    ["Vélo", "Trottinette"],
    ["Cinéma", "Théâtre"],
    ["Pizza", "Tarte"],
    ["Chat", "Tigre"],
    ["Mer", "Lac"],
    ["Bus", "Tramway"],
    ["Pull", "Manteau"],
    ["Crêpe", "Gaufre"],
    ["Guitare", "Ukulélé"],
    ["Médecin", "Vétérinaire"],
    ["Train", "Métro"],
    ["Jus de fruit", "Smoothie"],
    ["Bracelet", "Collier"],
    ["Plage", "Dune"],
    ["Neige", "Grêle"],
    ["Restaurant", "Cantine"],
    ["Tente", "Caravane"],
    ["Boulangerie", "Pâtisserie"],
    ["Roman", "Bande dessinée"],
    ["Casquette", "Chapeau"],
    ["Escalier", "Échelle"],
    ["Hôtel", "Auberge"],
    ["Lunettes", "Masque"],
    ["Piano", "Orgue"],
    ["Savon", "Shampoing"],
    ["Clé", "Cadenas"],
    ["Photo", "Peinture"],
    ["Yaourt", "Crème dessert"],
    ["Montagne", "Colline"],
    ["Professeur", "Entraîneur"],
    ["Valise", "Sac à dos"],
    ["Barbecue", "Four"],
    ["Pirate", "Viking"],
    ["Aspirateur", "Balai"],
    ["Chaussure", "Botte"],
    ["Parachute", "Parapente"],
    ["Bibliothèque", "Librairie"],
    ["Tomate", "Poivron"],
    ["Orange", "Pamplemousse"],
    ["Bougie", "Lampe"],
    ["Course à pied", "Randonnée"],
    ["Dessin animé", "Film"],
    ["Camion", "Fourgon"],
    ["Papillon", "Libellule"],
    ["Couverture", "Tapis"],
    ["Vague", "Marée"],
    ["Aquarium", "Zoo"],
    ["Poubelle", "Recyclage"],
    ["Mariage", "Bal"]
  ],

  difficile: [
    ["Barbe", "Moustache"],
    ["Brouillard", "Nuage"],
    ["Miroir", "Vitre"],
    ["Confiture", "Gelée"],
    ["Police", "Gendarmerie"],
    ["Crème", "Lotion"],
    ["Orange", "Clémentine"],
    ["Rire", "Sourire"],
    ["Abeille", "Guêpe"],
    ["Yaourt", "Fromage blanc"],
    ["Bibliothèque", "Médiathèque"],
    ["Sirop", "Miel"],
    ["Chuchoter", "Murmurer"],
    ["Veste", "Blouson"],
    ["Bocal", "Bouteille"],
    ["Tasse", "Mug"],
    ["Canapé", "Sofa"],
    ["Rêve", "Cauchemar"],
    ["Tempête", "Ouragan"],
    ["Sable", "Poussière"],
    ["Pirate", "Corsaire"],
    ["Sorcier", "Magicien"],
    ["Quai", "Ponton"],
    ["Mensonge", "Secret"],
    ["Bruine", "Averse"],
    ["Falaise", "Ravin"],
    ["Bâton", "Branche"],
    ["Carnet", "Agenda"],
    ["Parfum", "Eau de toilette"],
    ["Baiser", "Câlin"],
    ["Peur", "Angoisse"],
    ["Lampe", "Lanterne"],
    ["Sandale", "Tong"],
    ["Omelette", "Œufs brouillés"],
    ["Soupe", "Velouté"],
    ["Jumeau", "Sosie"],
    ["Gâteau", "Cake"],
    ["Crayon", "Stylo"],
    ["Tapis", "Paillasson"],
    ["Flaque", "Mare"],
    ["Rideau", "Store"],
    ["Clé", "Badge"],
    ["Salade", "Crudités"],
    ["Couloir", "Passage"],
    ["Silence", "Calme"],
    ["Grotte", "Tunnel"],
    ["Écharpe", "Foulard"],
    ["Chef", "Patron"],
    ["Voisin", "Colocataire"],
    ["Souvenir", "Nostalgie"]
  ]
};
