/* =========================================================
   UNDERCOVER — Dictionnaire de paires de mots (français)
   ---------------------------------------------------------
   Chaque paire contient deux mots proches : les civils
   reçoivent l'un, les undercovers reçoivent l'autre.
   L'ordre des deux mots n'a pas d'importance : le jeu tire
   au sort lequel revient aux civils.

   Niveaux de difficulté :
   - facile    : même famille (deux animaux, deux métiers, deux lieux...)
                 mais aux antipodes l'un de l'autre, si bien que l'imposteur
                 se trahit dès sa première description.
   - moyen     : même famille d'idées, il faut rester vague.
   - difficile : mots quasi synonymes, bluff obligatoire.
   ========================================================= */

const UNDERCOVER_WORDS = {
  facile: [
    ["Chien", "Poisson rouge"],
    ["Lion", "Souris"],
    ["Éléphant", "Fourmi"],
    ["Tortue", "Guépard"],
    ["Aigle", "Pingouin"],
    ["Baleine", "Abeille"],
    ["Vache", "Requin"],
    ["Girafe", "Hérisson"],
    ["Perroquet", "Crocodile"],
    ["Kangourou", "Escargot"],
    ["Avion", "Vélo"],
    ["Fusée", "Trottinette"],
    ["Bateau", "Train"],
    ["Hélicoptère", "Skateboard"],
    ["Métro", "Montgolfière"],
    ["Sous-marin", "Tracteur"],
    ["Pizza", "Salade"],
    ["Hamburger", "Sushi"],
    ["Gâteau", "Soupe"],
    ["Glace", "Piment"],
    ["Chocolat", "Citron"],
    ["Frites", "Yaourt"],
    ["Pastèque", "Noix"],
    ["Miel", "Vinaigre"],
    ["Spaghetti", "Kebab"],
    ["Café", "Limonade"],
    ["Champagne", "Eau du robinet"],
    ["Bière", "Chocolat chaud"],
    ["Pompier", "Boulanger"],
    ["Astronaute", "Plombier"],
    ["Dentiste", "Jardinier"],
    ["Juge", "Clown"],
    ["Chirurgien", "Coiffeur"],
    ["Pilote", "Berger"],
    ["Policier", "Danseur"],
    ["Château", "Cabane"],
    ["Hôpital", "Discothèque"],
    ["Bibliothèque", "Stade"],
    ["Désert", "Banquise"],
    ["Plage", "Volcan"],
    ["Prison", "Parc d'attractions"],
    ["Église", "Casino"],
    ["Aéroport", "Ferme"],
    ["Pyjama", "Costume"],
    ["Maillot de bain", "Doudoune"],
    ["Robe de mariée", "Combinaison de plongée"],
    ["Écharpe", "Ceinture"],
    ["Casque", "Chapeau de paille"],
    ["Football", "Échecs"],
    ["Boxe", "Yoga"],
    ["Natation", "Escalade"],
    ["Marathon", "Pétanque"],
    ["Ski", "Surf"],
    ["Guitare", "Tambour"],
    ["Piano", "Flûte"],
    ["Trompette", "Harmonica"],
    ["Neige", "Canicule"],
    ["Orage", "Arc-en-ciel"],
    ["Ouragan", "Brise"],
    ["Volcan", "Glacier"],
    ["Perceuse", "Pinceau"],
    ["Ventilateur", "Radiateur"],
    ["Lit", "Tabouret"],
    ["Trône", "Pouf"],
    ["Lampe", "Cheminée"],
    ["Ordinateur", "Machine à écrire"],
    ["Téléphone", "Pigeon voyageur"],
    ["Parapluie", "Lunettes de soleil"],
    ["Coffre-fort", "Boîte à chaussures"],
    ["Balai", "Lave-vaisselle"],
    ["Cinéma", "Karaoké"],
    ["Puzzle", "Montagnes russes"],
    ["Jeu de cartes", "Paintball"],
    ["Mariage", "Enterrement"],
    ["Noël", "Rentrée des classes"],
    ["Rose", "Cactus"],
    ["Chêne", "Champignon"],
    ["Sapin", "Palmier"],
    ["Dentifrice", "Parfum"],
    ["Savon", "Maquillage"],
    ["Mathématiques", "Sport"],
    ["Récréation", "Examen"],
    ["Réveil", "Sablier"],
    ["Télévision", "Livre"],
    ["Drone", "Cerf-volant"],
    ["Banque", "Boulangerie"],
    ["Centre commercial", "Marché aux puces"],
    ["Océan", "Flaque"],
    ["Baignoire", "Dé à coudre"],
    ["Gratte-ciel", "Niche"],
    ["Soleil", "Lune"],
    ["Étoile filante", "Trou noir"],
    ["Été", "Hiver"],
    ["Aube", "Minuit"],
    ["Seconde", "Siècle"],
    ["Joie", "Peur"],
    ["Colère", "Ennui"],
    ["Pont", "Tunnel"],
    ["Escalier", "Toboggan"],
    ["Feu d'artifice", "Bougie d'anniversaire"]
  ],

  moyen: [
    ["Café", "Thé"],
    ["Vélo", "Trottinette"],
    ["Cinéma", "Théâtre"],
    ["Pizza", "Tarte"],
    ["Chat", "Tigre"],
    ["Mer", "Lac"],
    ["Bus", "Tramway"],
    ["Pull", "Manteau"],
    ["Crêpe", "Gaufre"],
    ["Guitare", "Ukulélé"],
    ["Médecin", "Vétérinaire"],
    ["Train", "Métro"],
    ["Jus de fruit", "Smoothie"],
    ["Bracelet", "Collier"],
    ["Plage", "Dune"],
    ["Neige", "Grêle"],
    ["Restaurant", "Cantine"],
    ["Tente", "Caravane"],
    ["Boulangerie", "Pâtisserie"],
    ["Roman", "Bande dessinée"],
    ["Casquette", "Chapeau"],
    ["Escalier", "Échelle"],
    ["Hôtel", "Auberge"],
    ["Lunettes", "Masque"],
    ["Piano", "Orgue"],
    ["Savon", "Shampoing"],
    ["Clé", "Cadenas"],
    ["Photo", "Peinture"],
    ["Yaourt", "Crème dessert"],
    ["Montagne", "Colline"],
    ["Professeur", "Entraîneur"],
    ["Valise", "Sac à dos"],
    ["Barbecue", "Four"],
    ["Pirate", "Viking"],
    ["Aspirateur", "Balai"],
    ["Chaussure", "Botte"],
    ["Parachute", "Parapente"],
    ["Bibliothèque", "Librairie"],
    ["Tomate", "Poivron"],
    ["Orange", "Pamplemousse"],
    ["Bougie", "Lampe"],
    ["Course à pied", "Randonnée"],
    ["Dessin animé", "Film"],
    ["Camion", "Fourgon"],
    ["Papillon", "Libellule"],
    ["Couverture", "Tapis"],
    ["Vague", "Marée"],
    ["Aquarium", "Zoo"],
    ["Poubelle", "Recyclage"],
    ["Mariage", "Bal"],
    ["Chien", "Loup"],
    ["Fleuve", "Ruisseau"],
    ["Bière", "Cidre"],
    ["Poulet", "Dinde"],
    ["Baskets", "Chaussons"],
    ["Château fort", "Prison"],
    ["Pompier", "Secouriste"],
    ["Radio", "Podcast"],
    ["Bureau", "Atelier"],
    ["Piscine", "Patinoire"],
    ["Sandwich", "Wrap"],
    ["Cheval", "Âne"],
    ["Tarte", "Clafoutis"],
    ["Ski", "Snowboard"],
    ["Ordinateur", "Tablette"],
    ["Poupée", "Marionnette"],
    ["Cravate", "Nœud papillon"],
    ["Éclair", "Tonnerre"],
    ["Mouton", "Chèvre"],
    ["Riz", "Semoule"],
    ["Lettre", "Carte postale"],
    ["Jardin", "Balcon"],
    ["Serpent", "Lézard"],
    ["Crevette", "Crabe"],
    ["Bague", "Boucle d'oreille"],
    ["Pelle", "Râteau"],
    ["Jeu vidéo", "Flipper"],
    ["Église", "Mosquée"],
    ["Croissant", "Brioche"],
    ["Parapluie", "Imperméable"],
    ["Chorale", "Fanfare"],
    ["Poivre", "Piment"],
    ["Corde", "Chaîne"],
    ["Vinyle", "Cassette"],
    ["Pantalon", "Short"],
    ["Bulle", "Ballon de baudruche"],
    ["Feuille", "Pétale"],
    ["Trottoir", "Piste cyclable"],
    ["Bonhomme de neige", "Épouvantail"],
    ["Violon", "Harpe"],
    ["Marché", "Brocante"],
    ["Cuisinier", "Serveur"],
    ["Ampoule", "Néon"],
    ["Pomme", "Poire"],
    ["Loutre", "Castor"],
    ["Stade", "Arène"],
    ["Clinique", "Laboratoire"],
    ["Chaussette", "Collant"],
    ["Ferry", "Barque"],
    ["Perruque", "Bonnet"]
  ],

  difficile: [
    ["Barbe", "Moustache"],
    ["Brouillard", "Nuage"],
    ["Miroir", "Vitre"],
    ["Confiture", "Gelée"],
    ["Police", "Gendarmerie"],
    ["Crème", "Lotion"],
    ["Orange", "Clémentine"],
    ["Rire", "Sourire"],
    ["Abeille", "Guêpe"],
    ["Yaourt", "Fromage blanc"],
    ["Bibliothèque", "Médiathèque"],
    ["Sirop", "Miel"],
    ["Chuchoter", "Murmurer"],
    ["Veste", "Blouson"],
    ["Bocal", "Bouteille"],
    ["Tasse", "Mug"],
    ["Canapé", "Sofa"],
    ["Rêve", "Cauchemar"],
    ["Tempête", "Ouragan"],
    ["Sable", "Poussière"],
    ["Pirate", "Corsaire"],
    ["Sorcier", "Magicien"],
    ["Quai", "Ponton"],
    ["Mensonge", "Secret"],
    ["Bruine", "Averse"],
    ["Falaise", "Ravin"],
    ["Bâton", "Branche"],
    ["Carnet", "Agenda"],
    ["Parfum", "Eau de toilette"],
    ["Baiser", "Câlin"],
    ["Peur", "Angoisse"],
    ["Lampe", "Lanterne"],
    ["Sandale", "Tong"],
    ["Omelette", "Œufs brouillés"],
    ["Soupe", "Velouté"],
    ["Jumeau", "Sosie"],
    ["Gâteau", "Cake"],
    ["Crayon", "Stylo"],
    ["Tapis", "Paillasson"],
    ["Flaque", "Mare"],
    ["Rideau", "Store"],
    ["Clé", "Badge"],
    ["Salade", "Crudités"],
    ["Couloir", "Passage"],
    ["Silence", "Calme"],
    ["Grotte", "Tunnel"],
    ["Écharpe", "Foulard"],
    ["Chef", "Patron"],
    ["Voisin", "Colocataire"],
    ["Souvenir", "Nostalgie"],
    ["Serrure", "Verrou"],
    ["Télésiège", "Téléphérique"],
    ["Violon", "Alto"],
    ["Batterie", "Percussions"],
    ["Tarte", "Quiche"],
    ["Flacon", "Fiole"],
    ["Nappe", "Set de table"],
    ["Sentier", "Chemin"],
    ["Butte", "Monticule"],
    ["Ondée", "Giboulée"],
    ["Soupçon", "Doute"],
    ["Panne", "Bug"],
    ["Sieste", "Somnolence"],
    ["Ruse", "Astuce"],
    ["Blague", "Anecdote"],
    ["Cousin", "Neveu"],
    ["Fiancé", "Conjoint"],
    ["Bureau", "Pupitre"],
    ["Tabouret", "Pouf"],
    ["Coussin", "Traversin"],
    ["Serviette", "Torchon"],
    ["Boue", "Vase"],
    ["Étang", "Bassin"],
    ["Ruche", "Nid"],
    ["Cri", "Hurlement"],
    ["Odeur", "Arôme"],
    ["Colle", "Scotch"],
    ["Ficelle", "Fil"],
    ["Pince", "Tenaille"],
    ["Visière", "Bandeau"],
    ["Doudoune", "Anorak"],
    ["Chausson", "Pantoufle"],
    ["Bonnet", "Cagoule"],
    ["Brume", "Buée"],
    ["Verglas", "Givre"],
    ["Chenille", "Ver"],
    ["Corbeau", "Corneille"],
    ["Mouette", "Goéland"],
    ["Lapin", "Lièvre"],
    ["Grenouille", "Crapaud"],
    ["Papier", "Carton"],
    ["Marmite", "Cocotte"],
    ["Louche", "Spatule"],
    ["Confidence", "Aveu"],
    ["Rancune", "Regret"],
    ["Clin d'œil", "Grimace"],
    ["Ruelle", "Impasse"],
    ["Garage", "Hangar"],
    ["Cave", "Sous-sol"],
    ["Balcon", "Terrasse"]
  ]
};
