/* =========================================================
   UNDERCOVER — Dictionnaire de paires de mots (français)
   ---------------------------------------------------------
   Chaque paire contient deux mots proches : les civils
   reçoivent l'un, les undercovers reçoivent l'autre.
   L'ordre des deux mots n'a pas d'importance : le jeu tire
   au sort lequel revient aux civils.

   Niveaux de difficulté :
   - facile    : les deux mots n'ont presque rien en commun,
                 l'imposteur se trahit très vite.
   - moyen     : même famille d'idées, il faut rester vague.
   - difficile : mots quasi synonymes, bluff obligatoire.
   ========================================================= */

const UNDERCOVER_WORDS = {
  facile: [
    ["Chien", "Poisson"],
    ["Soleil", "Parapluie"],
    ["Pizza", "Salade"],
    ["Guitare", "Tambour"],
    ["Avion", "Vélo"],
    ["Plage", "Bibliothèque"],
    ["Neige", "Désert"],
    ["Chocolat", "Citron"],
    ["Montre", "Oreiller"],
    ["Football", "Échecs"],
    ["Pompier", "Boulanger"],
    ["Château", "Cabane"],
    ["Téléphone", "Bougie"],
    ["Lion", "Lapin"],
    ["Café", "Soupe"],
    ["Mariage", "Examen"],
    ["Voiture", "Cheval"],
    ["Supermarché", "Musée"],
    ["Glace", "Barbecue"],
    ["Clavier", "Pinceau"],
    ["Dentiste", "Jardinier"],
    ["Ascenseur", "Échelle"],
    ["Pyjama", "Costume"],
    ["Orage", "Arc-en-ciel"],
    ["Banque", "Boulangerie"],
    ["Astronaute", "Plombier"],
    ["Crayon", "Marteau"],
    ["Forêt", "Métro"],
    ["Miel", "Vinaigre"],
    ["Tortue", "Guépard"],
    ["Aéroport", "Camping"],
    ["Télévision", "Cheminée"],
    ["Moustique", "Éléphant"],
    ["Pluie", "Feu de camp"],
    ["Hôpital", "Discothèque"],
    ["Fromage", "Dentifrice"],
    ["Bateau", "Fusée"],
    ["Sieste", "Marathon"],
    ["Fourchette", "Savon"],
    ["Cirque", "Tribunal"],
    ["Ampoule", "Chaussette"],
    ["Balançoire", "Tondeuse"],
    ["Anniversaire", "Déménagement"],
    ["Pastèque", "Poivre"],
    ["Tunnel", "Montgolfière"],
    ["Journal", "Trampoline"],
    ["Ninja", "Bibliothécaire"],
    ["Réveil", "Hamac"],
    ["Souris", "Requin"],
    ["Parfum", "Poubelle"],
    ["Ballon", "Aspirateur"],
    ["Piscine", "Volcan"],
    ["Vache", "Hélicoptère"],
    ["Miroir", "Saucisson"],
    ["Écharpe", "Ventilateur"],
    ["Gâteau", "Tournevis"],
    ["Panda", "Tracteur"],
    ["Karaoké", "Déclaration d'impôts"],
    ["Télescope", "Papier toilette"],
    ["Chaussure", "Nuage"],
    ["Pharmacie", "Skatepark"],
    ["Confiture", "Béton"],
    ["Sorcière", "Comptable"],
    ["Hiver", "Piment"],
    ["Trompette", "Passoire"],
    ["Zèbre", "Calculatrice"],
    ["Coiffeur", "Chauffeur de bus"],
    ["Escargot", "Avion de chasse"],
    ["Moutarde", "Doudoune"],
    ["Bowling", "Opéra"],
    ["Château de sable", "Centrale nucléaire"],
    ["Chewing-gum", "Tronçonneuse"],
    ["Hamster", "Gratte-ciel"],
    ["Yoga", "Rodéo"],
    ["Citrouille", "Clarinette"],
    ["Facteur", "Dompteur"],
    ["Toboggan", "Coffre-fort"],
    ["Kebab", "Manucure"],
    ["Pingouin", "Sahara"],
    ["Moufle", "Sauna"],
    ["Craie", "Mixeur"],
    ["Déguisement", "Radiateur"],
    ["Poney", "Sous-marin"],
    ["Loterie", "Repassage"],
    ["Cactus", "Trombone"],
    ["Cascade", "Interrupteur"],
    ["Gymnase", "Cimetière"],
    ["Spaghetti", "Perceuse"],
    ["Astrologie", "Mécanique"],
    ["Feu d'artifice", "Salle d'attente"],
    ["Kangourou", "Machine à laver"],
    ["Nounours", "Extincteur"],
    ["Enclume", "Nénuphar"],
    ["Patinoire", "Fourmilière"],
    ["Casserole", "Vélodrome"],
    ["Dragon", "Machine à café"],
    ["Chapiteau", "Parking souterrain"],
    ["Sirène", "Livreur de pizzas"],
    ["Momie", "Baby-foot"],
    ["Fête foraine", "Salle d'opération"]
  ],

  moyen: [
    ["Café", "Thé"],
    ["Vélo", "Trottinette"],
    ["Cinéma", "Théâtre"],
    ["Pizza", "Tarte"],
    ["Chat", "Tigre"],
    ["Mer", "Lac"],
    ["Bus", "Tramway"],
    ["Pull", "Manteau"],
    ["Crêpe", "Gaufre"],
    ["Guitare", "Ukulélé"],
    ["Médecin", "Vétérinaire"],
    ["Train", "Métro"],
    ["Jus de fruit", "Smoothie"],
    ["Bracelet", "Collier"],
    ["Plage", "Dune"],
    ["Neige", "Grêle"],
    ["Restaurant", "Cantine"],
    ["Tente", "Caravane"],
    ["Boulangerie", "Pâtisserie"],
    ["Roman", "Bande dessinée"],
    ["Casquette", "Chapeau"],
    ["Escalier", "Échelle"],
    ["Hôtel", "Auberge"],
    ["Lunettes", "Masque"],
    ["Piano", "Orgue"],
    ["Savon", "Shampoing"],
    ["Clé", "Cadenas"],
    ["Photo", "Peinture"],
    ["Yaourt", "Crème dessert"],
    ["Montagne", "Colline"],
    ["Professeur", "Entraîneur"],
    ["Valise", "Sac à dos"],
    ["Barbecue", "Four"],
    ["Pirate", "Viking"],
    ["Aspirateur", "Balai"],
    ["Chaussure", "Botte"],
    ["Parachute", "Parapente"],
    ["Bibliothèque", "Librairie"],
    ["Tomate", "Poivron"],
    ["Orange", "Pamplemousse"],
    ["Bougie", "Lampe"],
    ["Course à pied", "Randonnée"],
    ["Dessin animé", "Film"],
    ["Camion", "Fourgon"],
    ["Papillon", "Libellule"],
    ["Couverture", "Tapis"],
    ["Vague", "Marée"],
    ["Aquarium", "Zoo"],
    ["Poubelle", "Recyclage"],
    ["Mariage", "Bal"],
    ["Chien", "Loup"],
    ["Fleuve", "Ruisseau"],
    ["Bière", "Cidre"],
    ["Poulet", "Dinde"],
    ["Baskets", "Chaussons"],
    ["Château fort", "Prison"],
    ["Pompier", "Secouriste"],
    ["Radio", "Podcast"],
    ["Bureau", "Atelier"],
    ["Piscine", "Patinoire"],
    ["Sandwich", "Wrap"],
    ["Cheval", "Âne"],
    ["Tarte", "Clafoutis"],
    ["Ski", "Snowboard"],
    ["Ordinateur", "Tablette"],
    ["Poupée", "Marionnette"],
    ["Cravate", "Nœud papillon"],
    ["Éclair", "Tonnerre"],
    ["Mouton", "Chèvre"],
    ["Riz", "Semoule"],
    ["Lettre", "Carte postale"],
    ["Jardin", "Balcon"],
    ["Serpent", "Lézard"],
    ["Crevette", "Crabe"],
    ["Bague", "Boucle d'oreille"],
    ["Pelle", "Râteau"],
    ["Jeu vidéo", "Flipper"],
    ["Église", "Mosquée"],
    ["Croissant", "Brioche"],
    ["Parapluie", "Imperméable"],
    ["Chorale", "Fanfare"],
    ["Poivre", "Piment"],
    ["Corde", "Chaîne"],
    ["Vinyle", "Cassette"],
    ["Pantalon", "Short"],
    ["Bulle", "Ballon de baudruche"],
    ["Feuille", "Pétale"],
    ["Trottoir", "Piste cyclable"],
    ["Bonhomme de neige", "Épouvantail"],
    ["Violon", "Harpe"],
    ["Marché", "Brocante"],
    ["Cuisinier", "Serveur"],
    ["Ampoule", "Néon"],
    ["Pomme", "Poire"],
    ["Loutre", "Castor"],
    ["Stade", "Arène"],
    ["Clinique", "Laboratoire"],
    ["Chaussette", "Collant"],
    ["Ferry", "Barque"],
    ["Perruque", "Bonnet"]
  ],

  difficile: [
    ["Barbe", "Moustache"],
    ["Brouillard", "Nuage"],
    ["Miroir", "Vitre"],
    ["Confiture", "Gelée"],
    ["Police", "Gendarmerie"],
    ["Crème", "Lotion"],
    ["Orange", "Clémentine"],
    ["Rire", "Sourire"],
    ["Abeille", "Guêpe"],
    ["Yaourt", "Fromage blanc"],
    ["Bibliothèque", "Médiathèque"],
    ["Sirop", "Miel"],
    ["Chuchoter", "Murmurer"],
    ["Veste", "Blouson"],
    ["Bocal", "Bouteille"],
    ["Tasse", "Mug"],
    ["Canapé", "Sofa"],
    ["Rêve", "Cauchemar"],
    ["Tempête", "Ouragan"],
    ["Sable", "Poussière"],
    ["Pirate", "Corsaire"],
    ["Sorcier", "Magicien"],
    ["Quai", "Ponton"],
    ["Mensonge", "Secret"],
    ["Bruine", "Averse"],
    ["Falaise", "Ravin"],
    ["Bâton", "Branche"],
    ["Carnet", "Agenda"],
    ["Parfum", "Eau de toilette"],
    ["Baiser", "Câlin"],
    ["Peur", "Angoisse"],
    ["Lampe", "Lanterne"],
    ["Sandale", "Tong"],
    ["Omelette", "Œufs brouillés"],
    ["Soupe", "Velouté"],
    ["Jumeau", "Sosie"],
    ["Gâteau", "Cake"],
    ["Crayon", "Stylo"],
    ["Tapis", "Paillasson"],
    ["Flaque", "Mare"],
    ["Rideau", "Store"],
    ["Clé", "Badge"],
    ["Salade", "Crudités"],
    ["Couloir", "Passage"],
    ["Silence", "Calme"],
    ["Grotte", "Tunnel"],
    ["Écharpe", "Foulard"],
    ["Chef", "Patron"],
    ["Voisin", "Colocataire"],
    ["Souvenir", "Nostalgie"],
    ["Serrure", "Verrou"],
    ["Télésiège", "Téléphérique"],
    ["Violon", "Alto"],
    ["Batterie", "Percussions"],
    ["Tarte", "Quiche"],
    ["Flacon", "Fiole"],
    ["Nappe", "Set de table"],
    ["Sentier", "Chemin"],
    ["Butte", "Monticule"],
    ["Ondée", "Giboulée"],
    ["Soupçon", "Doute"],
    ["Panne", "Bug"],
    ["Sieste", "Somnolence"],
    ["Ruse", "Astuce"],
    ["Blague", "Anecdote"],
    ["Cousin", "Neveu"],
    ["Fiancé", "Conjoint"],
    ["Bureau", "Pupitre"],
    ["Tabouret", "Pouf"],
    ["Coussin", "Traversin"],
    ["Serviette", "Torchon"],
    ["Boue", "Vase"],
    ["Étang", "Bassin"],
    ["Ruche", "Nid"],
    ["Cri", "Hurlement"],
    ["Odeur", "Arôme"],
    ["Colle", "Scotch"],
    ["Ficelle", "Fil"],
    ["Pince", "Tenaille"],
    ["Visière", "Bandeau"],
    ["Doudoune", "Anorak"],
    ["Chausson", "Pantoufle"],
    ["Bonnet", "Cagoule"],
    ["Brume", "Buée"],
    ["Verglas", "Givre"],
    ["Chenille", "Ver"],
    ["Corbeau", "Corneille"],
    ["Mouette", "Goéland"],
    ["Lapin", "Lièvre"],
    ["Grenouille", "Crapaud"],
    ["Papier", "Carton"],
    ["Marmite", "Cocotte"],
    ["Louche", "Spatule"],
    ["Confidence", "Aveu"],
    ["Rancune", "Regret"],
    ["Clin d'œil", "Grimace"],
    ["Ruelle", "Impasse"],
    ["Garage", "Hangar"],
    ["Cave", "Sous-sol"],
    ["Balcon", "Terrasse"]
  ]
};
